// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

// Load .env.local if it exists (for local development)
try {
  require("dotenv").config({ path: ".env.local" });
} catch (e) {
  // .env.local doesn't exist, that's okay
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"] || "postgresql://postgres:postgres@localhost:5432/lumosity_leaderboard",
  },
});
